Limit PDF generation max thread to 2
kazooo/fofola pull request #13
Opened 2022-09-05 13:21 UTC by MichaelTran262

- Also added WAITING state for PDF generation.

Note: Kramerius API allows only two PDF generation at the same time for a single user.

2022-09-05 13:24 UTC, MichaelTran262 commented
Nevím jestli `AsyncConfiguration.java` ovlivňuje i jiné procesy mimo `AsyncPDFGenService.java`, který jako jediný má `@Async` anotaci.

2022-09-11 13:44 UTC, kazooo requested changes
Also, vsude parametry/promenne pridej modifier `final` at jsou to konstanty (good practice).

2022-09-11 13:44 UTC, kazooo commented on backend/src/main/java/cz/mzk/fofola/model/pdf/PDFGenState.java
> +
zbytecny new line

2022-09-11 13:44 UTC, kazooo commented on backend/src/main/java/cz/mzk/fofola/configuration/AsyncConfiguration.java
> +
zbytecny new line

2022-09-11 13:44 UTC, kazooo commented on backend/src/main/java/cz/mzk/fofola/rest/PDFController.java
> +        pdfGenService.start(uuid, null, genLog);
prosim nechat strucne komentare, ze davas nejdriv do stavu `WAITING` protoze dal muze cekat na dalsi thread nez prejde do `ACTIVE`

2022-09-11 13:44 UTC, kazooo commented on frontend/src/modules/pdf/PdfFileList.js
> +    const readyToDownload = state => state !== 'EXCEPTION' && state !== 'ACTIVE' && state !== 'WAITING';
pecka :+1:

2022-09-11 13:44 UTC, kazooo commented on backend/src/main/java/cz/mzk/fofola/configuration/AsyncConfiguration.java
> +    public Executor taskExecutor() {
Tim vytvaris globalni taskExecutor pro celou appku, a to na 2 vlakna, coz urcite pro celou appku neni vhodny. Potrebujes tenhle taskExecutor jen pro generovani PDF, dej beanu nazev a ten specifikuj v @Async PDF generatoru, vic https://www.baeldung.com/spring-async#1-override-the-executor-at-the-method-level

2022-09-13 11:39 UTC, closed without merging